//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNIT.ProjetoEstag.Exercicio2.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEXO
    {
        public SEXO()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int ID_SEXO { get; set; }
        public string DS_SEXO { get; set; }
    
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
