//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNIT.ProjetoEstag.Exercicio2.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string DS_USUARIO { get; set; }
        public Nullable<int> ID_SEXO { get; set; }
        public Nullable<int> ID_ESTADO_CIVIL { get; set; }
    
        public virtual ESTADO_CIVIL ESTADO_CIVIL { get; set; }
        public virtual SEXO SEXO { get; set; }
    }
}
